### ISSUE TITLE
Order can't be placed due to Totals discrepancy

### ISSUE THREAD

**Issue by adam-0** [mvenghaus/magento2-hyva-checkout-amazon-pay#1]
Orders with the coupon code added after a user logged in to his Amazon account are cancelled due to discrepancy in Grand Total.

Adobe Commerce ver. 2.4.6-p6
Amazon Pay 5.18.0
Hyva Checkout 1.1.26 
Hyvä Compatibility module for Amazon_Pay, dev-dev

- Add to cart
- Go to checkout or select Amazon Pay Express Checkout
- Fill shipping and billing forms
- Select the shipping method
- Select Amazon Pay
- Log into Amazon account -> redirects back to checkout
- Apply the discount coupon code OR change shipping method
- Place order by clicking Pay with AmazonPay
- Error caused by Grand Total mismatch because value pulled in Amazon does not match updated totals on checkout page

**Comment by mvenghaus** [comment]
I am unfortunately no longer working on this module. We couldn’t agree on how the module should function, sorry!

However, the steps you provided seems a little bit odd. This sequence isn’t possible!?

Normally, the Amazon button should appear either in the shopping cart or before the shipping address.

-> Amazon Pay Button
-> Amazon website with address and payment selection
-> Hyva Checkout -> pre-filled shipping address
-> Continue to Payment - but no option to change the payment method
